src/app/urls.py
from django.conf.urls import url


from .views import (
    immage_add,
    )

urlpatterns = [
    url(r'^$', immage_add, name='image'),

]

src/mahdil/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
# from app.views import immage_add
# from .views import immage_add

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include("app.urls", namespace='app')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/app/models.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals
from django.utils.translation import ugettext_lazy as _
from django.core.urlresolvers import reverse
from django.db import models


class Image(models.Model):

    title = models.CharField(
        max_length=240,
        verbose_name='Post title',
        unique=True,
        )
    # Attributes
    # image = models.ImageField(
    #     _('image'),
    #     upload_to='images/%Y/%m/%d'
    # )
    # Meta Data
    created_on = models.DateTimeField(
        _('created on'),
        auto_now_add=True,
        editable=False,
        null=True,
    )
    updated_on = models.DateTimeField(
        _('updated on'),
        auto_now=True,
        editable=False,
        null=True,
    )

    # Meta
    class Meta:
        ordering = ['id']
        verbose_name = _('image')
        verbose_name_plural = _('images')

    # Functions
    def __str__(self):
        return "%s" % (self.id)

    def __unicode__(self):
        return "%s" % (self.id)

src/app/forms.py
# -*- coding: utf-8 -*-

from django import forms
from django.utils.translation import ugettext_lazy as _

from . import models
import django.db.models


class ImageForm(forms.ModelForm):
    class Meta:
        model = models.Image
        # image = forms.ImageField(
        #     required=True,
        # )

        fields = [
            'title',
        ]

src/app/views.py
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
import json
from django.core import serializers
# Create your views here.

from .forms import ImageForm
from .models import Image


def immage_add(request):
    form = ImageForm(request.POST or None, request.FILES or None)
    context = {
        "form": form
    }
    if request.method == 'POST':
        if form.is_valid():
            obj = form.save(commit=False)
            obj.save()
            qs = Image.objects.all()
            print("qs___________")
            print(qs)
            ajaxData = {}
            ajaxData['msg'] = 'Created a new blog post!'
            ajaxData['data'] = serializers.serialize('json', qs)
            # ajaxData['data'] = str(qs) //for image
            # json.dumps(qs.__dict__)
            return HttpResponse(json.dumps(ajaxData))
        else:
            ajaxData = {}
            ajaxData['msg'] = 'Sorry no data saved!'
            return HttpResponse(json.dumps(ajaxData))
    template = "image_add.html"
    return render(request, template, context)

src/app/templates/image_add.html
{% if messages %}
<ul class="messages">
	{% for message in messages %}
	<li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
	{% endfor %}
</ul>
{% endif %}

<div class="reply"></div>


<h1>Create new Post</h1>


<form id="blog_create" method='POST' action='.'>{% csrf_token %}
	{{ form.as_p }}

	<input id="formSubmit" type='submit' value='Create' >
</form>

<div class="post_list"></div>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<script type="text/javascript">

	$('#formSubmit').click(function(e){
		e.preventDefault();
		// console.log('test');
		var url = "{% url 'app:image' %}";
		var data = $('#blog_create').serialize();
		fromSubmit(url, data);
	});

	var fromSubmit= function(url, data){
		// console.info('fromSubmit');
		// console.info(data);

		$.ajax({
			type : "POST",
			url : url,
			dataType : "json",
			data : data,
			// cache : false,
			success : function(data) {
				// console.info('response.data');
				// console.info(data);
				$('.reply').html(data.msg);
				if (data.data){				
					var postList = JSON.parse(data.data);
					var postListLi = '<ul>';
					postList.forEach(function(entry) {
					    // console.log(entry);
					    // console.info(entry.fields.title);
					    postListLi +='<li>'+entry.fields.title+'</li>';
					});

					postListLi +='</ul>';

					// console.info(postListLi);
					$('.post_list').html(postListLi);
					$('#blog_create')[0].reset();
					}

			},
			error : function(XMLHttpRequest, textStatus, errorThrown) {
				// console.log(XMLHttpRequest.responseText);
			}
		});
  }// END OF fromSubmit= function(){
//||_____________________________________________________________________________________||
//||__<END>_______________________FOR___REST___OF____ATRIBUTE___________________________//
</script>